-- 1. Create table
CREATE TABLE CUSTOMER (
    CUST_NO NUMBER(4) PRIMARY KEY,
    FIRST_NAME VARCHAR2(20) NOT NULL,
    LAST_NAME VARCHAR2(20),
    ADDRESS VARCHAR2(20),
    CITY VARCHAR2(8),
    STATE VARCHAR2(20),
    PIN NUMBER(6),
    B_DATE DATE,
    STATUS CHAR(1) CHECK (STATUS IN ('V','I','A'))
);

-- 3. Display all records
SELECT * FROM CUSTOMER;

-- 4. Records where state is Karnataka
SELECT * FROM CUSTOMER WHERE STATE = 'KARNATAKA';

-- 5. Delete row with PIN 576201
DELETE FROM CUSTOMER WHERE PIN = 576201;

-- 6. Update PIN
UPDATE CUSTOMER SET PIN = 476001 WHERE CUST_NO = 1004;

-- 7. Update address and PIN
UPDATE CUSTOMER 
SET ADDRESS = 'KAVI MUDDANNA MARG', PIN = 576104
WHERE CUST_NO = 1003;

-- 8. Delete Goa records and retrieve
DELETE FROM CUSTOMER WHERE STATE = 'GOA';
SELECT * FROM CUSTOMER;

-- 9. Invalid persons
SELECT * FROM CUSTOMER WHERE STATUS = 'I';

-- 10. Distinct states
SELECT DISTINCT STATE FROM CUSTOMER;

-- 11. Sort by state (ascending)
SELECT * FROM CUSTOMER ORDER BY STATE ASC;

-- 12. Sort state descending
SELECT STATE FROM CUSTOMER ORDER BY STATE DESC;

-- 13. Karnataka valid customers
SELECT * FROM CUSTOMER 
WHERE STATE = 'KARNATAKA' AND STATUS = 'V';

-- 14. Karnataka or Kerala customers
SELECT * FROM CUSTOMER 
WHERE STATE IN ('KARNATAKA','KERALA');

-- 15. Active Karnataka/Kerala customers
SELECT * FROM CUSTOMER 
WHERE STATE IN ('KARNATAKA','KERALA') AND STATUS = 'A';

-- 16. Karnataka customers with PIN 576201
SELECT * FROM CUSTOMER 
WHERE STATE = 'KARNATAKA' AND PIN = 576201;

-- 17. Exclude customer 1005
SELECT * FROM CUSTOMER WHERE CUST_NO <> 1005;

-- 18. State starting with K
SELECT * FROM CUSTOMER WHERE STATE LIKE 'K%';

-- 19. Name contains 'RAJ'
SELECT * FROM CUSTOMER WHERE FIRST_NAME LIKE '%RAJ%';

-- 20. CUST_NO between 1003 and 1005
SELECT * FROM CUSTOMER WHERE CUST_NO BETWEEN 1003 AND 1005;

-- 21. Date range
SELECT * FROM CUSTOMER 
WHERE B_DATE BETWEEN '10-JAN-71' AND '31-DEC-71';

-- 22. Specific cities
SELECT * FROM CUSTOMER 
WHERE CITY IN ('UDP','MNG','BNG','PGN');

-- 23. Rename table
RENAME CUSTOMER TO CUST;